import type { Character, Enemy, Quest, Summon, Weapon } from './types';

export const initialCharacters: Character[] = [
  {
    id: 'char-leya-ember-rail',
    name: '莱娅·赤轨',
    element: 'fire',
    rarity: 'SSR',
    level: 1,
    maxLevel: 150,
    stats: { hp: 1180, atk: 780, defense: 100 },
    assetKey: 'character/leya-ember-rail',
    bondTags: ['赤轨', '奥义'],
    passives: [
      {
        id: 'passive-leya-solar-oath',
        name: '日冕誓约',
        description: '提升星印攻刃。',
        modifiers: [
          {
            id: 'mod-leya-normal-atk',
            label: '星印攻刃 +8%',
            type: 'attack',
            value: 0.08,
            category: 'normal',
            source: 'character',
          },
        ],
      },
      {
        id: 'passive-leya-charge-loop',
        name: '赤轨回流',
        description: '提升奥义充能效率。',
        modifiers: [
          {
            id: 'mod-leya-charge-gain',
            label: '奥义获得量 +10%',
            type: 'chargeGain',
            value: 0.1,
            source: 'character',
          },
        ],
      },
    ],
    chargeAttack: { id: 'ca-leya', name: '赤轨断层', multiplier: 4.5, chargeCost: 100, cap: 1160000 },
  },
  {
    id: 'char-caro-furnace',
    name: '卡洛·炉心',
    element: 'fire',
    rarity: 'SR',
    level: 1,
    maxLevel: 150,
    stats: { hp: 1320, atk: 610, defense: 112 },
    assetKey: 'character/caro-furnace',
    bondTags: ['炉心', '防御', '赤轨'],
    passives: [
      {
        id: 'passive-caro-guard',
        name: '耐热装甲',
        description: '提升防御力。',
        modifiers: [
          {
            id: 'mod-caro-defense',
            label: '防御 +10%',
            type: 'defense',
            value: 0.1,
            source: 'character',
          },
        ],
      },
      {
        id: 'passive-caro-hp',
        name: '炉压稳定',
        description: '提升最大 HP。',
        modifiers: [
          {
            id: 'mod-caro-hp',
            label: '星印守护 +8%',
            type: 'hp',
            value: 0.08,
            category: 'normal',
            source: 'character',
          },
        ],
      },
    ],
    chargeAttack: { id: 'ca-caro', name: '炉心重击', multiplier: 3.8, chargeCost: 100, cap: 920000 },
  },
  {
    id: 'char-mira-astral-circuit',
    name: '米菈·星回路',
    element: 'fire',
    rarity: 'SSR',
    level: 1,
    maxLevel: 150,
    stats: { hp: 1040, atk: 840, defense: 92 },
    assetKey: 'character/mira-astral-circuit',
    bondTags: ['星回', '奥义', '赤轨', '灰烬'],
    passives: [
      {
        id: 'passive-mira-crit',
        name: '星火演算',
        description: '提升暴击率。',
        modifiers: [
          {
            id: 'mod-mira-crit-rate',
            label: '暴击率 +12%',
            type: 'criticalRate',
            value: 0.12,
            source: 'character',
          },
        ],
      },
      {
        id: 'passive-mira-ca-cap',
        name: '回路过载',
        description: '提升奥义伤害上限。',
        modifiers: [
          {
            id: 'mod-mira-ca-cap',
            label: '奥义上限 +8%',
            type: 'chargeCap',
            value: 0.08,
            source: 'character',
          },
        ],
      },
    ],
    chargeAttack: { id: 'ca-mira', name: '星火协议', multiplier: 4.7, chargeCost: 100, cap: 1220000 },
  },
  {
    id: 'char-noin-ash-protocol',
    name: '诺因·灰烬协议',
    element: 'fire',
    rarity: 'SR',
    level: 1,
    maxLevel: 150,
    stats: { hp: 980, atk: 690, defense: 88 },
    assetKey: 'character/noin-ash-protocol',
    bondTags: ['灰烬', '资源', '炉心'],
    passives: [
      {
        id: 'passive-noin-da',
        name: '热相同步',
        description: '提升连击率。',
        modifiers: [
          {
            id: 'mod-noin-da',
            label: 'DA 率 +10%',
            type: 'doubleAttackRate',
            value: 0.1,
            source: 'character',
          },
        ],
      },
      {
        id: 'passive-noin-drop',
        name: '残响检索',
        description: '提升掉落率。',
        modifiers: [
          {
            id: 'mod-noin-drop',
            label: '掉落率 +5%',
            type: 'dropRate',
            value: 0.05,
            source: 'character',
          },
        ],
      },
    ],
    chargeAttack: { id: 'ca-noin', name: '灰烬脉冲', multiplier: 3.9, chargeCost: 100, cap: 940000 },
  },
];

export const initialWeapons: Weapon[] = [
  {
    id: 'weapon-red-rail-saber',
    name: '赤轨誓剑',
    element: 'fire',
    rarity: 'SSR',
    source: 'story',
    level: 1,
    maxLevel: 150,
    stats: { hp: 120, atk: 410, defense: 0 },
    assetKey: 'weapon/red-rail-saber',
    skills: [
      {
        id: 'skill-red-rail-normal',
        name: '赤轨星印刃',
        level: 1,
        modifiers: [
          {
            id: 'mod-red-rail-normal',
            label: '星印攻刃 +8%',
            type: 'attack',
            value: 0.08,
            category: 'normal',
            source: 'weapon',
          },
        ],
      },
    ],
  },
  {
    id: 'weapon-furnace-grid-blade',
    name: '第七炉心刃',
    element: 'fire',
    rarity: 'SSR',
    source: 'farmable',
    level: 1,
    maxLevel: 150,
    stats: { hp: 96, atk: 390, defense: 0 },
    assetKey: 'weapon/furnace-grid-blade',
    skills: [
      {
        id: 'skill-furnace-magna',
        name: '炉心方阵攻刃',
        level: 1,
        modifiers: [
          {
            id: 'mod-furnace-magna',
            label: '方阵攻刃 +7%',
            type: 'attack',
            value: 0.07,
            category: 'magna',
            source: 'weapon',
          },
        ],
      },
    ],
  },
];

export const initialSummons: Summon[] = [
  {
    id: 'summon-helios-engine',
    name: '赫曜机神',
    element: 'fire',
    rarity: 'SSR',
    level: 1,
    maxLevel: 150,
    stats: { hp: 380, atk: 960, defense: 0 },
    aura: { label: '方阵技能效果提升 50%', target: 'magna', boost: 0.5 },
    assetKey: 'summon/helios-engine',
  },
  {
    id: 'summon-aurora-core',
    name: '赤曦炉核',
    element: 'fire',
    rarity: 'SSR',
    level: 1,
    maxLevel: 150,
    stats: { hp: 420, atk: 880, defense: 0 },
    aura: { label: '星印技能效果提升 40%', target: 'normal', boost: 0.4 },
    assetKey: 'summon/aurora-core',
  },
];

export const initialEnemies: Enemy[] = [
  {
    id: 'enemy-wind-sentinel-1',
    name: '风蚀守卫 I',
    element: 'wind',
    stats: { hp: 48000, atk: 520, defense: 100 },
    normalAttackDamage: 260,
    assetKey: 'enemy/wind-sentinel-1',
    chargeMax: 3,
    specialActions: [
      {
        id: 'wind-sentinel-1-charge',
        name: '涡流穿刺',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 1.3,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-2',
    name: '风蚀守卫 II',
    element: 'wind',
    stats: { hp: 118000, atk: 980, defense: 112 },
    normalAttackDamage: 540,
    assetKey: 'enemy/wind-sentinel-2',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-2-hp-50',
        name: '裂风阈震',
        trigger: { kind: 'hpThreshold', threshold: 0.5 },
        target: { kind: 'all' },
        damageMultiplier: 1.2,
      },
      {
        id: 'wind-sentinel-2-charge',
        name: '满豆风压',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 1.4,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-3',
    name: '风蚀守卫 III',
    element: 'wind',
    stats: { hp: 260000, atk: 1650, defense: 125 },
    normalAttackDamage: 940,
    assetKey: 'enemy/wind-sentinel-3',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-3-hp-75',
        name: '星轨割裂',
        trigger: { kind: 'hpThreshold', threshold: 0.75 },
        target: { kind: 'randomN', count: 2 },
        damageMultiplier: 1.25,
      },
      {
        id: 'wind-sentinel-3-hp-35',
        name: '断面风暴',
        trigger: { kind: 'hpThreshold', threshold: 0.35 },
        target: { kind: 'all' },
        damageMultiplier: 1.45,
      },
      {
        id: 'wind-sentinel-3-charge',
        name: '满豆天压',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 1.6,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-4',
    name: '风蚀堡垒兵 I',
    element: 'wind',
    stats: { hp: 420000, atk: 2140, defense: 138 },
    normalAttackDamage: 1180,
    assetKey: 'enemy/wind-sentinel-4',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-4-hp-60',
        name: '风幕压切',
        trigger: { kind: 'hpThreshold', threshold: 0.6 },
        target: { kind: 'all' },
        damageMultiplier: 1.28,
      },
      {
        id: 'wind-sentinel-4-charge',
        name: '满豆裂城风炮',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 1.72,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-5',
    name: '风蚀堡垒兵 II',
    element: 'wind',
    stats: { hp: 680000, atk: 2780, defense: 152 },
    normalAttackDamage: 1480,
    assetKey: 'enemy/wind-sentinel-5',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-5-hp-70',
        name: '双重风界',
        trigger: { kind: 'hpThreshold', threshold: 0.7 },
        target: { kind: 'randomN', count: 2 },
        damageMultiplier: 1.34,
      },
      {
        id: 'wind-sentinel-5-hp-40',
        name: '堡垒坍缩',
        trigger: { kind: 'hpThreshold', threshold: 0.4 },
        target: { kind: 'all' },
        damageMultiplier: 1.52,
      },
      {
        id: 'wind-sentinel-5-charge',
        name: '满豆风蚀坠枪',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 1.85,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-6',
    name: '风蚀暴君',
    element: 'wind',
    stats: { hp: 1100000, atk: 3520, defense: 168 },
    normalAttackDamage: 1880,
    assetKey: 'enemy/wind-sentinel-6',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-6-hp-75',
        name: '裂穹风压',
        trigger: { kind: 'hpThreshold', threshold: 0.75 },
        target: { kind: 'randomN', count: 2 },
        damageMultiplier: 1.42,
      },
      {
        id: 'wind-sentinel-6-hp-50',
        name: '灭层断界',
        trigger: { kind: 'hpThreshold', threshold: 0.5 },
        target: { kind: 'all' },
        damageMultiplier: 1.66,
      },
      {
        id: 'wind-sentinel-6-hp-25',
        name: '风王极刑',
        trigger: { kind: 'hpThreshold', threshold: 0.25 },
        target: { kind: 'all' },
        damageMultiplier: 1.88,
      },
      {
        id: 'wind-sentinel-6-charge',
        name: '满豆终末天压',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 2.05,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-7',
    name: '风蚀暴君·狂相',
    element: 'wind',
    stats: { hp: 1620000, atk: 4280, defense: 182 },
    normalAttackDamage: 2260,
    assetKey: 'enemy/wind-sentinel-7',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-7-hp-80',
        name: '狂相裂域',
        trigger: { kind: 'hpThreshold', threshold: 0.8 },
        target: { kind: 'randomN', count: 2 },
        damageMultiplier: 1.46,
      },
      {
        id: 'wind-sentinel-7-hp-45',
        name: '风狱重压',
        trigger: { kind: 'hpThreshold', threshold: 0.45 },
        target: { kind: 'all' },
        damageMultiplier: 1.74,
      },
      {
        id: 'wind-sentinel-7-charge',
        name: '满豆裂穹坠',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 2.16,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-8',
    name: '风蚀王座兵器',
    element: 'wind',
    stats: { hp: 2380000, atk: 5080, defense: 198 },
    normalAttackDamage: 2720,
    assetKey: 'enemy/wind-sentinel-8',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-8-hp-75',
        name: '王座切断',
        trigger: { kind: 'hpThreshold', threshold: 0.75 },
        target: { kind: 'randomN', count: 3 },
        damageMultiplier: 1.52,
      },
      {
        id: 'wind-sentinel-8-hp-50',
        name: '风冠失衡',
        trigger: { kind: 'hpThreshold', threshold: 0.5 },
        target: { kind: 'all' },
        damageMultiplier: 1.82,
      },
      {
        id: 'wind-sentinel-8-hp-20',
        name: '终冠暴落',
        trigger: { kind: 'hpThreshold', threshold: 0.2 },
        target: { kind: 'all' },
        damageMultiplier: 2.02,
      },
      {
        id: 'wind-sentinel-8-charge',
        name: '满豆王座风枪',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 2.24,
      },
    ],
  },
  {
    id: 'enemy-wind-sentinel-9',
    name: '风蚀真核',
    element: 'wind',
    stats: { hp: 3300000, atk: 5960, defense: 214 },
    normalAttackDamage: 3240,
    assetKey: 'enemy/wind-sentinel-9',
    chargeMax: 2,
    specialActions: [
      {
        id: 'wind-sentinel-9-hp-80',
        name: '真核脉裂',
        trigger: { kind: 'hpThreshold', threshold: 0.8 },
        target: { kind: 'randomN', count: 3 },
        damageMultiplier: 1.6,
      },
      {
        id: 'wind-sentinel-9-hp-55',
        name: '风蚀终层',
        trigger: { kind: 'hpThreshold', threshold: 0.55 },
        target: { kind: 'all' },
        damageMultiplier: 1.92,
      },
      {
        id: 'wind-sentinel-9-hp-25',
        name: '真核坍塌',
        trigger: { kind: 'hpThreshold', threshold: 0.25 },
        target: { kind: 'all' },
        damageMultiplier: 2.18,
      },
      {
        id: 'wind-sentinel-9-charge',
        name: '满豆终焉风蚀',
        trigger: { kind: 'chargeFull' },
        target: { kind: 'single' },
        damageMultiplier: 2.36,
      },
    ],
  },
];

export const initialQuests: Quest[] = [
  {
    id: 'quest-main-1',
    name: '主线 1：风蚀外缘',
    kind: 'main',
    element: 'wind',
    difficulty: 1,
    runDurationMs: 5 * 60_000,
    enemyId: 'enemy-wind-sentinel-1',
    firstClearRewards: [{ itemId: 'crystal', kind: 'currency', quantity: 300, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 2, chance: 0.55 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 2, chance: 0.65 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.08 },
    ],
  },
  {
    id: 'quest-main-2',
    name: '主线 2：裂风回廊',
    kind: 'main',
    element: 'wind',
    difficulty: 2,
    runDurationMs: 7 * 60_000,
    enemyId: 'enemy-wind-sentinel-2',
    unlockAfterQuestId: 'quest-main-1',
    firstClearRewards: [{ itemId: 'gacha-ticket', kind: 'currency', quantity: 1, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 2, chance: 0.6 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 2, chance: 0.75 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 2, chance: 0.6 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.12 },
    ],
  },
  {
    id: 'quest-main-3',
    name: '主线 3：星轨断面',
    kind: 'main',
    element: 'wind',
    difficulty: 3,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-3',
    unlockAfterQuestId: 'quest-main-2',
    firstClearRewards: [{ itemId: 'crystal', kind: 'currency', quantity: 600, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 3, chance: 0.68 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 3, chance: 0.78 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 3, chance: 0.7 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 1, chance: 0.22 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.03 },
    ],
  },
  {
    id: 'quest-main-4',
    name: '主线 4：裂界风塔',
    kind: 'main',
    element: 'wind',
    difficulty: 4,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-4',
    unlockAfterQuestId: 'quest-main-3',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 800, chance: 1 },
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 6, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 4, chance: 0.72 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 4, chance: 0.82 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 4, chance: 0.78 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.18 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 2, chance: 0.55 },
    ],
  },
  {
    id: 'quest-main-5',
    name: '主线 5：涡心兵站',
    kind: 'main',
    element: 'wind',
    difficulty: 5,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-5',
    unlockAfterQuestId: 'quest-main-4',
    firstClearRewards: [
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 2, chance: 1 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 8, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 4, chance: 0.74 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 5, chance: 0.84 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 5, chance: 0.82 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.22 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 2, chance: 0.52 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.05 },
    ],
  },
  {
    id: 'quest-main-6',
    name: '主线 6：天压中枢',
    kind: 'main',
    element: 'wind',
    difficulty: 6,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-6',
    unlockAfterQuestId: 'quest-main-5',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 1200, chance: 1 },
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 2, chance: 1 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 8, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 5, chance: 0.78 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 6, chance: 0.86 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 6, chance: 0.86 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.24 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 3, chance: 0.55 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.06 },
    ],
  },
  {
    id: 'quest-main-7',
    name: '主线 7：狂相风狱',
    kind: 'main',
    element: 'wind',
    difficulty: 7,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-7',
    unlockAfterQuestId: 'quest-main-6',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 1400, chance: 1 },
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 10, chance: 1 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 4, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 6, chance: 0.82 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 7, chance: 0.88 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 7, chance: 0.88 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.26 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 1, chance: 0.2 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 3, chance: 0.6 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.07 },
    ],
  },
  {
    id: 'quest-main-8',
    name: '主线 8：王座风冠',
    kind: 'main',
    element: 'wind',
    difficulty: 8,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-8',
    unlockAfterQuestId: 'quest-main-7',
    firstClearRewards: [
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 3, chance: 1 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 12, chance: 1 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 12, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 7, chance: 0.84 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 8, chance: 0.9 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 8, chance: 0.9 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.28 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 1, chance: 0.22 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 4, chance: 0.64 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.08 },
    ],
  },
  {
    id: 'quest-main-9',
    name: '主线 9：真核终层',
    kind: 'main',
    element: 'wind',
    difficulty: 9,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-9',
    unlockAfterQuestId: 'quest-main-8',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 1800, chance: 1 },
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 3, chance: 1 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 4, chance: 1 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 4, chance: 1 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 4, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 8, chance: 0.86 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 9, chance: 0.92 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 9, chance: 0.92 },
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.3 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 1, chance: 0.28 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 1, chance: 0.28 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 1, chance: 0.24 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 4, chance: 0.68 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.09 },
    ],
  },
  {
    id: 'quest-boss-wind-1',
    name: '讨伐：裂风守卫核',
    kind: 'boss',
    element: 'wind',
    difficulty: 2,
    runDurationMs: 8 * 60_000,
    enemyId: 'enemy-wind-sentinel-2',
    unlockAfterQuestId: 'quest-main-1',
    firstClearRewards: [{ itemId: 'crystal', kind: 'currency', quantity: 200, chance: 1 }],
    dropTable: [
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.12 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.03 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 1, chance: 0.35 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 1, chance: 0.3 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 1, chance: 0.24 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 1, chance: 0.32 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 4, chance: 0.6 },
    ],
  },
  {
    id: 'quest-boss-wind-2',
    name: '讨伐：裂界风塔核心',
    kind: 'boss',
    element: 'wind',
    difficulty: 4,
    runDurationMs: 9 * 60_000,
    enemyId: 'enemy-wind-sentinel-4',
    unlockAfterQuestId: 'quest-main-3',
    firstClearRewards: [{ itemId: 'crystal', kind: 'currency', quantity: 350, chance: 1 }],
    dropTable: [
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.18 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.05 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 2, chance: 0.42 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 2, chance: 0.36 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 2, chance: 0.3 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 2, chance: 0.48 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 6, chance: 0.68 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 6, chance: 0.62 },
    ],
  },
  {
    id: 'quest-boss-wind-3',
    name: '讨伐：风蚀暴君',
    kind: 'boss',
    element: 'wind',
    difficulty: 6,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-6',
    unlockAfterQuestId: 'quest-main-5',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 500, chance: 1 },
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 1, chance: 1 },
    ],
    dropTable: [
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.24 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.07 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 3, chance: 0.52 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 3, chance: 0.45 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 3, chance: 0.4 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 3, chance: 0.55 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 8, chance: 0.72 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 8, chance: 0.68 },
    ],
  },
  {
    id: 'quest-boss-wind-4',
    name: '讨伐：王座风冠兵器',
    kind: 'boss',
    element: 'wind',
    difficulty: 8,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-8',
    unlockAfterQuestId: 'quest-main-7',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 700, chance: 1 },
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 1, chance: 1 },
    ],
    dropTable: [
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.28 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.08 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 4, chance: 0.62 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 4, chance: 0.56 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 4, chance: 0.5 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 4, chance: 0.66 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 10, chance: 0.78 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 10, chance: 0.74 },
    ],
  },
  {
    id: 'quest-boss-wind-5',
    name: '讨伐：风蚀真核',
    kind: 'boss',
    element: 'wind',
    difficulty: 9,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-9',
    unlockAfterQuestId: 'quest-main-9',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 1000, chance: 1 },
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 2, chance: 1 },
    ],
    dropTable: [
      { itemId: 'weapon-furnace-grid-blade', kind: 'weapon', quantity: 1, chance: 0.32 },
      { itemId: 'summon-helios-engine', kind: 'summon', quantity: 1, chance: 0.1 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 5, chance: 0.72 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 5, chance: 0.64 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 5, chance: 0.58 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 5, chance: 0.72 },
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 8, chance: 0.78 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 12, chance: 0.82 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 12, chance: 0.8 },
    ],
  },
  {
    id: 'quest-material-wind-1',
    name: '采集：风蚀残响带',
    kind: 'material',
    element: 'wind',
    difficulty: 1,
    runDurationMs: 6 * 60_000,
    enemyId: 'enemy-wind-sentinel-1',
    unlockAfterQuestId: 'quest-main-1',
    firstClearRewards: [{ itemId: 'gacha-ticket', kind: 'currency', quantity: 1, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 2, chance: 0.55 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 3, chance: 0.9 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 3, chance: 0.9 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 1, chance: 0.45 },
    ],
  },
  {
    id: 'quest-material-wind-2',
    name: '采集：裂界风塔仓段',
    kind: 'material',
    element: 'wind',
    difficulty: 3,
    runDurationMs: 8 * 60_000,
    enemyId: 'enemy-wind-sentinel-4',
    unlockAfterQuestId: 'quest-main-2',
    firstClearRewards: [{ itemId: 'gacha-ticket', kind: 'currency', quantity: 1, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 4, chance: 0.9 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 5, chance: 0.92 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 5, chance: 0.92 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 2, chance: 0.58 },
    ],
  },
  {
    id: 'quest-material-wind-3',
    name: '采集：天压中枢废层',
    kind: 'material',
    element: 'wind',
    difficulty: 5,
    runDurationMs: 9 * 60_000,
    enemyId: 'enemy-wind-sentinel-5',
    unlockAfterQuestId: 'quest-main-4',
    firstClearRewards: [{ itemId: 'crystal', kind: 'currency', quantity: 250, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 6, chance: 0.95 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 7, chance: 0.95 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 7, chance: 0.95 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 3, chance: 0.65 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 1, chance: 0.28 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 1, chance: 0.24 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 1, chance: 0.2 },
    ],
  },
  {
    id: 'quest-material-wind-4',
    name: '采集：狂相风狱深层',
    kind: 'material',
    element: 'wind',
    difficulty: 7,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-7',
    unlockAfterQuestId: 'quest-main-6',
    firstClearRewards: [{ itemId: 'crystal', kind: 'currency', quantity: 320, chance: 1 }],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 8, chance: 0.96 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 9, chance: 0.96 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 9, chance: 0.96 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 4, chance: 0.72 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 2, chance: 0.34 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 2, chance: 0.3 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 2, chance: 0.28 },
    ],
  },
  {
    id: 'quest-material-wind-5',
    name: '采集：真核坍塌域',
    kind: 'material',
    element: 'wind',
    difficulty: 9,
    runDurationMs: 10 * 60_000,
    enemyId: 'enemy-wind-sentinel-9',
    unlockAfterQuestId: 'quest-main-8',
    firstClearRewards: [
      { itemId: 'crystal', kind: 'currency', quantity: 420, chance: 1 },
      { itemId: 'gacha-ticket', kind: 'currency', quantity: 1, chance: 1 },
    ],
    dropTable: [
      { itemId: 'fire-character-exp', kind: 'characterExp', quantity: 10, chance: 0.98 },
      { itemId: 'fire-weapon-exp', kind: 'weaponExpMaterial', quantity: 11, chance: 0.98 },
      { itemId: 'fire-summon-exp', kind: 'summonExpMaterial', quantity: 11, chance: 0.98 },
      { itemId: 'fire-weapon-skill', kind: 'weaponSkillMaterial', quantity: 5, chance: 0.8 },
      { itemId: 'fire-character-uncap', kind: 'characterUncapMaterial', quantity: 3, chance: 0.4 },
      { itemId: 'fire-weapon-uncap', kind: 'weaponUncapMaterial', quantity: 3, chance: 0.38 },
      { itemId: 'fire-summon-uncap', kind: 'summonUncapMaterial', quantity: 3, chance: 0.34 },
    ],
  },
];
